/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BsCardRectangle {
    'buttontext': string;
    'cardtitle': string;
    'image': string;
    'imageurl': string;
    'subtitle': string;
  }
  interface BsTabContent {}
  interface BsTabs {}
}

declare global {


  interface HTMLBsCardRectangleElement extends Components.BsCardRectangle, HTMLStencilElement {}
  var HTMLBsCardRectangleElement: {
    prototype: HTMLBsCardRectangleElement;
    new (): HTMLBsCardRectangleElement;
  };

  interface HTMLBsTabContentElement extends Components.BsTabContent, HTMLStencilElement {}
  var HTMLBsTabContentElement: {
    prototype: HTMLBsTabContentElement;
    new (): HTMLBsTabContentElement;
  };

  interface HTMLBsTabsElement extends Components.BsTabs, HTMLStencilElement {}
  var HTMLBsTabsElement: {
    prototype: HTMLBsTabsElement;
    new (): HTMLBsTabsElement;
  };
  interface HTMLElementTagNameMap {
    'bs-card-rectangle': HTMLBsCardRectangleElement;
    'bs-tab-content': HTMLBsTabContentElement;
    'bs-tabs': HTMLBsTabsElement;
  }
}

declare namespace LocalJSX {
  interface BsCardRectangle {
    'buttontext'?: string;
    'cardtitle'?: string;
    'image'?: string;
    'imageurl'?: string;
    'subtitle'?: string;
  }
  interface BsTabContent {}
  interface BsTabs {}

  interface IntrinsicElements {
    'bs-card-rectangle': BsCardRectangle;
    'bs-tab-content': BsTabContent;
    'bs-tabs': BsTabs;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'bs-card-rectangle': LocalJSX.BsCardRectangle & JSXBase.HTMLAttributes<HTMLBsCardRectangleElement>;
      'bs-tab-content': LocalJSX.BsTabContent & JSXBase.HTMLAttributes<HTMLBsTabContentElement>;
      'bs-tabs': LocalJSX.BsTabs & JSXBase.HTMLAttributes<HTMLBsTabsElement>;
    }
  }
}


