/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BsCardRectangle {
    'buttontext': string;
    'cardtitle': string;
    'image': string;
    'imageurl': string;
    'subtitle': string;
  }
}

declare global {


  interface HTMLBsCardRectangleElement extends Components.BsCardRectangle, HTMLStencilElement {}
  var HTMLBsCardRectangleElement: {
    prototype: HTMLBsCardRectangleElement;
    new (): HTMLBsCardRectangleElement;
  };
  interface HTMLElementTagNameMap {
    'bs-card-rectangle': HTMLBsCardRectangleElement;
  }
}

declare namespace LocalJSX {
  interface BsCardRectangle {
    'buttontext'?: string;
    'cardtitle'?: string;
    'image'?: string;
    'imageurl'?: string;
    'subtitle'?: string;
  }

  interface IntrinsicElements {
    'bs-card-rectangle': BsCardRectangle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'bs-card-rectangle': LocalJSX.BsCardRectangle & JSXBase.HTMLAttributes<HTMLBsCardRectangleElement>;
    }
  }
}


